[VCOM-3360] Fix TestAWSEndpointService
With this CL fix:
- TestAWSEndpointService.testCreateAndThenValidate:128 expected:<1> but was:<2>
- TestAWSEndpointService.testCreateEndpoint:108 expected:<...6a2f1f34efcd3d564360[42e5c45]>
  but was:<...6a2f1f34efcd3d564360[3f23da3]>

The test is changed to extend from BasicTestCase as opposite to BasicReusableHostTestCase,
so that every test runs against fresh DB (more specifically no Endpoints). Otherwise (since there
is no clean up after the test) there's mismatch between ComputeDesc.authLink and
EndpointState.authLink. Why? Cause ComputeDesc.authLink points to the auth of the EP created
by the previous run of the test.

Change-Id: I7909f894d3cc60cde215f88c0d99c9302f5684ab
JIRA: https://jira.eng.vmware.com/browse/VCOM-3360