Fixing 'Error triggering Azure enumeration adapter /provisioning/azure/storage-enumeration-adapter'
The following exception is frequently observed during Azure enum: Caused by:
com.microsoft.azure.storage.StorageException: The specified resource does not exist.
  at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:89)
  at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305)
  at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175)
  at com.microsoft.azure.storage.blob.CloudBlobClient.listContainersWithPrefixSegmented(CloudBlobClient.java:358)
  at com.microsoft.azure.storage.blob.CloudBlobClient.listContainersSegmented(CloudBlobClient.java:271)
  at com.vmware.photon.controller.model.adapters.azure.enumeration.AzureStorageEnumerationAdapterService.lambda
  $getStorageContainersAsync$56(AzureStorageEnumerationAdapterService.java:922)

It seems that while 'CloudBlobClient.listContainersSegmented' is reading storage containers
either storage account or storage container is being deleted (maybe caused by parallel test execution).

The fix (hopefully) handles that and just continues with next Storage Account.

Change-Id: I0e293fff632d4de0b60207ca1d9aea9ee6c0930f